### ISSUE TITLE
underflow error with HIV and `--brlen optimize`

### ISSUE THREAD

**Issue by skhilton** [jbloomlab/phydms#11] opened 2017-03-22 01:53 UTC
This error goes away if the branch lengths are scaled rather than optimized. 

I included the log file from the original failed run. 

[HIV_underflow.zip](https://github.com/jbloomlab/phydms/files/860146/HIV_underflow.zip)

**Comment by jbloom** [comment] 2017-03-25 22:30
@skhilton: I cannot reproduce the error. I'm not sure if this is because `RAxML` is giving me a different tree or I'm not running the right command. In any case, it's hard for me to tell what is giving your error because you say it happens when branch lengths are optimized but your example command has them scaled.

Can you provide a scaled-down file where you give just the `phydms` command that is giving the error along with the exact input files (tree, prefs, and alignment) that you are giving `phydms` and the shell command that you run to get this error.

**Comment by skhilton** [comment] 2017-03-26 04:40
@jbloom: here is just the `phydms` command with the branch lengths optimized. I re-ran the command and still got the error. 

[HIV_underflow.zip](https://github.com/jbloomlab/phydms/files/870563/HIV_underflow.zip)

**Comment by jbloom** [comment] 2017-03-27 00:15
Should be fixed by this commit, which increases the frequency with which the underflow correction is applied:
https://github.com/jbloomlab/phydms/commit/cd086b96f4d47cf623b4f972077e767bc1cdc4eb

**Closed by jbloom** 2017-03-27 00:15 UTC
